name:  NodeJs

on:
  push:
    branches: master


permissions: 
   security-events: write
   issues: write
   actions: read
   contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [18, 20, 22]
        exclude:
          - os: windows-latest
            node-version: 22

    steps: 
      - name:  Checkout Code
        uses:  actions/checkout@v7

      - name: Set up Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Build
        run: npm install

      - name: test
        run: npm test

          
      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
             package*
 
      - name: Cache Dependencies
        uses: actions/cache@v5
        with:
          path: ~/.npm
          key:  ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          
      - name: Deploy
        run: echo "code is deployed"


