name: nodejs
on:  
 push:
    branches: master

permissions: 
  security-events: write
  issues:   write
  actions: read
  contents: read 
  
jobs:
   build-test: 
    runs-on: ${{matrix.os}}

    strategy: 
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node-version: [18,20,22]
        exclude:
          - os: windows-latest
            node-version: 22 
        
    steps:
      - name: checkout
        uses: actions/checkout@v7
        
      - name: nodejs
        uses: actions/setup-node@v6
        with:
          node-version: '24' 
          
      - name: initialize codeql
        uses: github/codeql-action/init@v4
        with:
           language: javascript   

      - name: autobuild
        uses: github/codeql-action/autobuild@v4

      - name: run codeql analysis
        uses: github/codeql-action/analyze@v4 
      - name: cache dependencies
        uses: actions/cache@v5
        with:
           path: ~/.npm
           key: ${{runner.os}}-node-${{hashFiles('**/package-lock.json')}}
          
      - name: build
        run: npm install
        
      - name: test
        run: npm test
        
      - name: artifact
        uses: actions/upload-artifact@v7
        with:
           name: artifact-1
           path:  | 
                package*
    
      - name: deploy
        run: echo " heloo guru"
