name: CI

on:
  push:
    branches:
      - develop
      - test

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v4

      - run: echo "Deploying to Staging..."

  deploy-production:
    if: github.ref == 'refs/heads/test'
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - run: echo "Deploying to Production..."
